#ifndef INFERENCE_H
#define INFERENCE_H
#include <stdint.h>

typedef int8_t  weight_t;
typedef int32_t accum_t;

// Access the external symbols generated by objcopy
extern weight_t _binary_oracle_weights_bin_start;
extern weight_t _binary_oracle_weights_bin_end;

accum_t compute_layer(weight_t* weights, int8_t* inputs, uint32_t length);

#endif
