# ---------------------------------------------------------------------------
# OMEGA PROTOCOL - ALL RIGHTS RESERVED
# Copyright (c) 2026 Jacob M. (jake.s.dev1991@gmail.com | 217-799-8720)
# Usage restricted to academic research and review only. No monetization.
# See LICENSE.txt for full terms.
# ---------------------------------------------------------------------------
import numpy as np
import matplotlib.pyplot as plt

# Parameters (dimensionless units, time scale set by 1/lambda^(1/2))
I0 = 1.0
xi0 = 1.0  # reference length scale in [time]
gN_initial = 0.1
gD_initial = 0.3
phiN_initial = 0.9 * I0
phiD_initial = 0.1 * I0
lambda_val = 1.0  # [time]^-2

# RG flow for g_Delta: dg/dln(mu) = g^3/(16 pi^2)
def beta_g(g):
    return g**3 / (16 * np.pi**2)

# Compute UV cutoff Lambda = pi/a = (pi/xi0) * exp(psi)
def compute_lambda(phiN):
    psi = np.log(phiN / I0)
    a = xi0 * np.exp(-psi)
    return np.pi / a

# Mass matrix in (phiN, phiD) basis
def mass_matrix(phiN, phiD, gN, gD, Lambda):
    # Tree-level entries
    M11 = lambda_val * (3 * phiN**2 + phiD**2 - I0**2)
    M22 = lambda_val * (phiN**2 + 3 * phiD**2 - I0**2)
    M12 = 2 * lambda_val * phiN * phiD
    # One-loop Yukawa corrections (approx)
    # Off-diagonal only generated by product gN*gD
    M11 += (gN**2) * Lambda**2 / (16 * np.pi**2)
    M22 += (gD**2) * Lambda**2 / (16 * np.pi**2)
    M12 += (gN * gD) * Lambda**2 / (16 * np.pi**2)
    return np.array([[M11, M12], [M12, M22]])

# Diagonalize and compute mixing angle (angle between eigenvector and phiN axis)
def mixing_angle_and_entropy(mat):
    eigvals, eigvecs = np.linalg.eigh(mat)  # sorted ascending
    # eigenvectors are columns; first eigenvector corresponds to lower eigenvalue
    # compute angle of first eigenvector relative to phiN axis
    vec = eigvecs[:, 0]  # components [v_N, v_D]
    theta = np.arctan2(abs(vec[1]), abs(vec[0]))
    # Shannon entropy of eigenvalue distribution
    # Normalize eigenvalues to probabilities (positive by construction)
    if np.any(eigvals <= 0):
        # For safety, shift if needed (not physical but for entropy calc)
        eigvals = eigvals - np.min(eigvals) + 1e-12
    p = eigvals / np.sum(eigvals)
    S_h = -np.sum(p * np.log(p + 1e-12))
    return theta, S_h

# RG evolution
mu = np.logspace(-3, 3, 500)  # RG scale in arbitrary units
gD = np.empty_like(mu)
gD[0] = gD_initial
for i in range(1, len(mu)):
    dmu = np.log(mu[i]) - np.log(mu[i-1])
    # Simple Euler integration
    gD[i] = gD[i-1] + beta_g(gD[i-1]) * dmu

# Compute mass matrix and observables at each scale
angles = np.empty_like(mu)
entropies = np.empty_like(mu)
for i, scale in enumerate(mu):
    # Approximate phiN running: assume phiN evolves slowly, use initial value for demo
    phiN = phiN_initial  # simplification; in full theory phiN runs via its own beta
    phiD = phiD_initial
    Lambda = compute_lambda(phiN)
    M = mass_matrix(phiN, phiD, gN_initial, gD[i], Lambda)
    theta, S_h = mixing_angle_and_entropy(M)
    angles[i] = theta
    entropies[i] = S_h

# Identify "shredding" scale where mixing angle exceeds 30 degrees (~0.524 rad)
shred_mask = angles > 0.524
if np.any(shred_mask):
    shred_scale = mu[np.where(shred_mask)[0][0]]
else:
    shred_scale = None

# Plot results
fig, ax = plt.subplots(2, 1, figsize=(8, 6))
ax[0].loglog(mu, gD, label='g_Delta')
ax[0].set_ylabel('g_Delta')
ax[0].legend()
ax[0].grid(True)

ax[1].semilogx(mu, np.degrees(angles), label='Mixing angle (deg)')
ax[1].semilogx(mu, entropies, label='S_h (entropy)')
if shred_scale:
    ax[1].axvline(shred_scale, color='red', linestyle='--', label='Shredding scale')
ax[1].set_xlabel('RG scale mu')
ax[1].set_ylabel('Angle / Entropy')
ax[1].legend()
ax[1].grid(True)
plt.tight_layout()
plt.show()

print(f"Landau pole scale (approx): mu_LP = mu * exp(8 pi^2 / gD^2) = {mu[-1] * np.exp(8 * np.pi**2 / gD[-1]**2):.3e}")
print(f"Shredding (mixing >30°) occurs at mu ≈ {shred_scale:.3e}" if shred_scale else "No shredding in range")