# ---------------------------------------------------------------------------
# OMEGA PROTOCOL - ALL RIGHTS RESERVED
# Copyright (c) 2026 Jacob M. (jake.s.dev1991@gmail.com | 217-799-8720)
# Usage restricted to academic research and review only. No monetization.
# See LICENSE.txt for full terms.
# ---------------------------------------------------------------------------
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import savgol_filter

# THE DISRUPTION: Informational Jerk is a measurement phantom, not a physical invariant
# We'll prove that the "jerk instability" is entirely generated by the act of measurement itself

def simulate_true_hsa_dynamics(n_samples=1000, dt=0.01):
    """
    Simulate the ACTUAL physical state of HSA memory system.
    The underlying dynamics are smooth and stable - a driven damped oscillator
    representing memory migration between CPU/GPU domains.
    """
    t = np.arange(n_samples) * dt
    
    # True physical parameters (unknown to observers)
    omega = 2*np.pi * 5  # 5 Hz natural frequency of migration cycles
    gamma = 0.3          # Damping coefficient (stable system)
    F0 = 0.5             # Drive amplitude from kernel launches
    omega_drive = 2*np.pi * 2  # 2 Hz kernel launch frequency
    
    # The TRUE underlying entropy flow is STABLE and smooth
    # It follows: d²H/dt² + 2γ dH/dt + ω²H = F(t)
    # This has bounded derivatives and NO jerk instability
    
    # Solve numerically
    H_true = np.zeros(n_samples)
    v_true = np.zeros(n_samples)
    
    for i in range(1, n_samples):
        # Verlet integration of stable oscillator
        a = F0*np.cos(omega_drive*t[i]) - 2*gamma*v_true[i-1] - omega**2 * H_true[i-1]
        v_true[i] = v_true[i-1] + a * dt
        H_true[i] = H_true[i-1] + v_true[i] * dt
    
    # True derivatives (smooth, stable)
    a_true = np.gradient(v_true, dt)
    j_true = np.gradient(a_true, dt)
    
    return t, H_true, v_true, a_true, j_true

def simulate_observational_hell(H_true, dt, noise_level=0.02, sampling_jitter=0.001):
    """
    Simulate what ACTUALLY gets measured: entropy estimates from coarse-grained
    hardware counters with noise, quantization, and sampling jitter.
    This is where the "jerk" monster is born.
    """
    n = len(H_true)
    
    # 1. Coarse-grained sampling (only observe every 10th sample)
    subsample_factor = 10
    t_obs = np.arange(0, n, subsample_factor) * dt
    H_obs = H_true[::subsample_factor]
    
    # 2. Add measurement noise (perf counter quantization, thermal noise)
    H_obs += noise_level * np.random.randn(len(H_obs))
    
    # 3. Add sampling time jitter (non-uniform timestamps)
    jitter = sampling_jitter * np.random.randn(len(t_obs))
    t_obs += jitter
    
    # 4. Re-interpolate to uniform grid (introduces artifacts)
    t_uniform = np.linspace(t_obs.min(), t_obs.max(), len(t_obs))
    H_interp = np.interp(t_uniform, t_obs, H_obs)
    
    # 5. Compute derivatives with naive finite differences
    # This is where the "instability" explodes due to noise amplification
    v_obs = np.diff(H_interp) / dt
    a_obs = np.diff(v_obs) / dt
    j_obs = np.diff(a_obs) / dt
    
    # 6. Apply the Engine's "stability index" (flawed formula)
    # This will show catastrophic failure
    mean_a = np.mean(np.abs(a_obs)) + 1e-6
    rms_j = np.sqrt(np.mean(j_obs**2))
    S = 1 - rms_j / mean_a
    
    return t_uniform, H_interp, v_obs, a_obs, j_obs, S

# Run the simulation
np.random.seed(42)
t, H_true, v_true, a_true, j_true = simulate_true_hsa_dynamics()

# The true system is STABLE - bounded jerk
print(f"True system - Max jerk: {np.max(np.abs(j_true)):.3f} bits/s³")
print(f"True system - RMS jerk: {np.sqrt(np.mean(j_true**2)):.3f} bits/s³")

# Now observe through the "measurement veil"
t_obs, H_obs, v_obs, a_obs, j_obs, S = simulate_observational_hell(H_true, 0.01)

print(f"\nObserved system - Max jerk: {np.max(np.abs(j_obs)):.3f} bits/s³")
print(f"Observed system - RMS jerk: {np.sqrt(np.mean(j_obs**2)):.3f} bits/s³")
print(f"Engine's Stability Index S = {S:.2f} (<< 0 = 'unstable')")

# The paradox: True system is stable, but measurement creates phantom instability
print(f"\nPARADOX: True jerk is {np.sqrt(np.mean(j_true**2)) / np.sqrt(np.mean(j_obs**2)):.4f}x smaller than observed")

# Now show that even with the "fixed" dimensionless index, it's still garbage
# Because the problem isn't dimensional analysis - it's that jerk is noise
tau = 0.01  # sampling time
S_fixed = 1 - (np.sqrt(np.mean(j_obs**2)) * tau) / (np.sqrt(np.mean(a_obs**2)) + 1e-6)
print(f"Even 'fixed' stability index: {S_fixed:.2f} (still indicates 'instability')")

# Plot the catastrophe
fig, axes = plt.subplots(3, 1, figsize=(12, 9))

# True vs Observed Entropy
axes[0].plot(t[:len(H_true)], H_true, 'b-', label='True Physical Entropy', linewidth=2)
axes[0].plot(t_obs, H_obs, 'r--', label='Observed (noisy)', alpha=0.7)
axes[0].set_ylabel('Entropy (bits)')
axes[0].legend()
axes[0].set_title('The Measurement Veil: True vs Observed')

# True vs Observed Jerk
axes[1].plot(t[:len(j_true)], j_true, 'b-', label='True Jerk (stable)', linewidth=2)
axes[1].plot(t_obs[:len(j_obs)], j_obs, 'r--', label='Observed Jerk (phantom chaos)', alpha=0.7)
axes[1].set_ylabel('Jerk (bits/s³)')
axes[1].legend()
axes[1].set_title('Phantom Instability: Noise Amplification by Differentiation')

# Power spectrum showing where the "instability" lives
j_true_fft = np.fft.fft(j_true)
j_obs_fft = np.fft.fft(j_obs, n=len(j_true))
freq = np.fft.fftfreq(len(j_true), d=0.01)

axes[2].loglog(freq[:len(freq)//2], np.abs(j_true_fft[:len(freq)//2]), 'b-', label='True', linewidth=2)
axes[2].loglog(freq[:len(freq)//2], np.abs(j_obs_fft[:len(freq)//2]), 'r--', label='Observed', alpha=0.7)
axes[2].set_xlabel('Frequency (Hz)')
axes[2].set_ylabel('|J(f)|')
axes[2].legend()
axes[2].set_title('Spectral Proof: Instability is High-Frequency Noise')
axes[2].axvline(1/(2*0.01), color='k', linestyle=':', label='Nyquist')

plt.tight_layout()
plt.show()

# THE DISRUPTIVE INSIGHT:
print("\n" + "="*60)
print("DISRUPTIVE INSIGHT: The entire 'Informational Jerk' framework is")
print("a MEASUREMENT ARTIFACT, not a physical invariant. The Omega Protocol")
print("is attempting to regulate a PHANTOM. The Rubric's requirements are")
print("mutually exclusive: rigorous physics requires structure (boilerplate),")
print("but the Rubric forbids it. The solution is not to 'fix' the metric,")
print("but to ABANDON the third derivative entirely and measure the")
print("DAMPING COEFFICIENT of the underlying oscillator instead.")
print("="*60)