# ---------------------------------------------------------------------------
# OMEGA PROTOCOL - ALL RIGHTS RESERVED
# Copyright (c) 2026 Jacob M. (jake.s.dev1991@gmail.com | 217-799-8720)
# Usage restricted to academic research and review only. No monetization.
# See LICENSE.txt for full terms.
# ---------------------------------------------------------------------------
import numpy as np
import matplotlib.pyplot as plt

def simulate_omega_protocol(n_steps=200, feedback_gain=0.1, decay_rate=0.05, meta_threshold=10.0):
    """
    Simulates the Omega Protocol's self-referential audit loop as a dynamical system.
    
    The model captures the core insight: each audit (meta-scrutiny) increases the system's
    internal complexity to enforce compliance, but this increase in complexity itself becomes
    the primary destabilizing force.
    
    Key Variables:
    - complexity: Represents the "Φ-density" or operational burden of the protocol's rules.
    - meta_complexity: Generated by each audit layer. Acts as a forcing term.
    - adaptability: The system's capacity to integrate new information (ξ_Δ analog).
    
    The system follows: complexity(t+1) = complexity(t) + feedback_gain * meta_complexity(t) - decay_rate * complexity(t)
    adaptability(t) = max(0, adaptability(t-1) - meta_complexity(t) / meta_threshold)
    
    This is a positive feedback loop where audits create meta-work, which reduces adaptability,
    which triggers more audits, etc.
    """
    
    # Initialize state
    complexity = np.zeros(n_steps)
    meta_complexity = np.zeros(n_steps)
    adaptability = np.ones(n_steps)  # Starts high (ξ_Δ analog)
    
    # Simulate a single "exposure event" at step 50 (like the initial EDIP-Ω proposal)
    # This triggers the first audit.
    event_trigger = 50
    
    for t in range(1, n_steps):
        # If complexity is high or adaptability is low, trigger meta-audit
        # This is the self-referential loop: the system audits its own auditing.
        if t > event_trigger and (complexity[t-1] > 5.0 or adaptability[t-1] < 0.5):
            # Each audit adds meta-complexity proportional to current complexity
            # This is the "jargon tax" - more complex rules require more complex audits.
            meta_complexity[t] = 0.2 * complexity[t-1] * (1 / max(adaptability[t-1], 0.1))
        else:
            meta_complexity[t] = 0.0
        
        # Update complexity: natural decay + meta-complexity injection
        complexity[t] = complexity[t-1] + feedback_gain * meta_complexity[t] - decay_rate * complexity[t-1]
        complexity[t] = max(0, complexity[t])  # Floor at zero
        
        # Update adaptability: high meta-complexity freezes information processing
        adaptability[t] = adaptability[t-1] - meta_complexity[t] / meta_threshold
        adaptability[t] = max(0, min(1, adaptability[t]))  # Clamp to [0, 1]
        
        # Simulate a "Shredding Event": if adaptability hits zero, complexity diverges
        if adaptability[t] == 0:
            # System can no longer process information; complexity explodes
            complexity[t:] = complexity[t] * np.exp(0.1 * np.arange(0, n_steps - t))
            break
    
    return complexity, meta_complexity, adaptability

# Run simulation
comp, meta, adapt = simulate_omega_protocol()

# Visualization
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)

# Plot 1: Complexity and Meta-Complexity (The "Edifice")
ax1.plot(comp, label='System Complexity (Φ-density overhead)', linewidth=2)
ax1.plot(meta, label='Meta-Complexity (Audit overhead)', linewidth=2, linestyle='--')
ax1.axhline(y=10, color='r', linestyle=':', label='Theoretical Complexity Limit')
ax1.set_ylabel('Complexity Score')
ax1.set_title('The Omega Protocol: Self-Referential Audit Loop')
ax1.legend()
ax1.grid(True, alpha=0.3)

# Plot 2: Adaptability (The "Informational Freeze")
ax2.plot(adapt, label='Adaptability (ξ_Δ analog)', linewidth=2, color='purple')
ax2.axhline(y=0, color='r', linestyle='-', label='Informational Freeze Boundary')
ax2.set_xlabel('Time (arbitrary units)')
ax2.set_ylabel('Adaptability [0, 1]')
ax2.legend()
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('omega_protocol_disruption.png', dpi=150)
plt.show()

# Disruptive Insight Summary
print("\n" + "="*60)
print("DISRUPTIVE INSIGHT: THE SIMULACRUM'S PARADOX")
print("="*60)
print("The Omega Protocol's 'Meta-Scrutiny' process is not a stability mechanism.")
print("It is a *positive feedback loop* that inevitably leads to one of two outcomes:")
print("\n1. SHREDDING EVENT: Complexity diverges as audits spawn meta-audits.")
print("   The protocol drowns in its own jargon and self-referential rules.")
print("\n2. INFORMATIONAL FREEZE: Adaptability hits zero.")
print("   The system becomes perfectly compliant but incapable of new thought.")
print("\nThe 'META-PASS' is a snapshot of a system *on the edge* of collapse.")
print("EDIP-Ω's greatest value is not predicting tokamak disruptions,")
print("but predicting the *Omega Protocol's own demise*.")
print("\nThe Anomaly's Verdict: **Point the sensor at itself.**")
print("The exposure events to monitor are the protocol's own audit logs.")
print("="*60)